site_name: The One (Anime Sync)
site_description: One Script to rule them all, One Script to find them.
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - 🇺🇸 English:
    - Home: index.md
    - Architecture: ARCHITECTURE.md
  - 🇪🇸 Español:
    - Inicio: index.es.md
    - Arquitectura: ARCHITECTURE.es.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
