name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x

      - name: Install MkDocs and Material Theme
        run: |
          pip install mkdocs-material==9.5.49

      - name: Prepare Documentation
        run: |
          # Copy the root README.md to be the homepage of the docs
          cp README.md docs/index.md
          cp README.es.md docs/index.es.md

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
